language: objective-c
osx_image: xcode8.3
cache:
    directories:
    - $HOME/.ccache
install:
- brew install ccache
- PATH=$PATH:/usr/local/opt/ccache/libexec
script:
- set -o pipefail && xcodebuild -project "trash.xcodeproj" -scheme "trash" build analyze
before_script:
- ccache -s
- ccache -z
after_script:
- ccache -s
notifications:
    slack: xs-labs:FXh1yLXNkpcVxKZhZU6icdhI
